fix

diff --git a/.github/workflows/validate-fed-modules.yaml b/.github/workflows/validate-fed-modules.yaml
--- a/.github/workflows/validate-fed-modules.yaml
+++ b/.github/workflows/validate-fed-modules.yaml
@@ -17,15 +17,15 @@ jobs:
   validate:
     runs-on: ubuntu-20.04
     # prevents from running in forked repositories
-    if: github.repository_owner == 'RedHatInsights'
+    #if: github.repository_owner == 'RedHatInsights'
     steps:
       - name: Checkout Code Ref '${{ github.ref }}'
         uses: actions/checkout@v3
 
       - name: Run validation script
         run: |
-        ./.github/scripts/validate-fed-modules.sh
-        if [ "$?" -ne 0 ]; then
-          echo "Validation failed. Exiting workflow."
-          exit 1
-        fi
+           ./.github/scripts/validate-fed-modules.sh
+           if [ "$?" -ne 0 ]; then
+             echo "Validation failed. Exiting workflow."
+             exit 1
+           fi
